In [40]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [41]:
arr1

['pune', 'mumbai', 'surat', 'kolkata', 'bihar', 'jaipur', 'chennai']

In [42]:
print(arr1)

['pune', 'mumbai', 'surat', 'kolkata', 'bihar', 'jaipur', 'chennai']


In [43]:
type(arr1)

list

In [44]:
arr1[0]

'pune'

In [45]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [46]:
arr2

array([10, 20, 30, 40, 50])

In [47]:
print(arr2)

[10 20 30 40 50]


In [48]:
type(arr2)

numpy.ndarray

In [49]:
print(arr2)

[10 20 30 40 50]


In [50]:
arr2

array([10, 20, 30, 40, 50])

In [51]:
arr3 = numpy.array((100,200,300,400,500))

In [52]:
type(arr3)

numpy.ndarray

In [53]:
import numpy as np
a0 = np.array(10)

In [54]:
print(a0)

10


In [55]:
a0.ndim

0

In [56]:
a0

array(10)

In [57]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [58]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
a1.ndim
# # a1.ndim gives number of dimensions of the NumPy array


1

In [60]:
a1.shape 
a1.size
a1.dtype
a1.itemsize
a1.nbytes
a1.dtype.name
a1.astype('float64')
a1
a1.astype('int32')
a1.astype('int16')
a1.astype('int8')
a1.astype('uint8')
a1.astype('bool')
a1.astype('complex64')
a1.astype('complex128')
a1.astype('S4')
a1.astype('U4')
a1.astype('object')
a1.astype('float32')
a1.astype('float16')
a1.astype('float64')
a1.astype('int64')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [61]:
import numpy as np

a1 = np.array([1, 2, 3])

# a1.ndim → tells the number of dimensions (axes) of the array.
# For example: 
# 1D array → ndim = 1  (like [1,2,3])
# 2D array → ndim = 2  (like [[1,2,3],[4,5,6]])
# 3D array → ndim = 3  (like [[[1,2],[3,4]]])
print(a1.ndim)

1


In [62]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [63]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [64]:
a2 = np.array([
    [1, 2, 3],
    [10, 20, 30],
    [100, 200, 300],
    [1000, 2000, 3000]
])

# This creates a 2D NumPy array (matrix) with 4 rows and 3 columns:
# [
#   [1,     2,     3    ],
#   [10,    20,    30   ],
#   [100,   200,   300  ],
#   [1000,  2000,  3000 ]
# ]
# → Shape = (4, 3)
# → ndim = 2 (because it is a 2D array)
# → Each inner list represents one row


In [65]:
a2.ndim

2

In [66]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [67]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [68]:
a3.ndim

3

In [69]:
print("No. of dimensions:", a3.ndim)

No. of dimensions: 3


In [70]:
print("\033[91mNo. of dimensions:", a3.ndim, "\033[0m")
# --- IGNORE ---

No. of dimensions: 3 


In [71]:
print("\033[91mNo. of dimensions:", a3.ndim, "\033[0m")


No. of dimensions: 3 


In [72]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [73]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [74]:
a4.ndim

4

In [75]:
arr2 = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500]
])

print(arr2[0])     # → [10 20 30 40 50]
print(arr2[0][2])  # → 30


[10 20 30 40 50]
30


In [76]:
arr2[1],  [10,20,30,40,50]

(array([100, 200, 300, 400, 500]), [10, 20, 30, 40, 50])

In [77]:
a2[1,2], [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

(30, [[1, 2, 3], [10, 20, 30], [100, 200, 300], [1000, 2000, 3000]])

In [78]:
a2[2,2]

300

In [79]:
a3[0,0,0], [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

(1, [[[1, 2, 3], [10, 20, 30]], [[100, 200, 300], [1000, 2000, 3000]]])

In [80]:
a4[0,0,0,3]

4444

In [ ]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [ ]:
a12 = np.array([1,2,3])

In [ ]:
a12[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [ ]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
arr2

array([10, 20, 30, 40, 50])

In [ ]:
arr2[-1]

50

In [ ]:
arr2[-2]

40

In [ ]:
arr2[1:]

array([20, 30, 40, 50])

In [ ]:
arr2[:3]

array([10, 20, 30])

In [ ]:
arr2[:]

array([10, 20, 30, 40, 50])

In [ ]:
arr2[1:4:1]

array([20, 30, 40])

In [ ]:
arr2[1:4:2]

array([20, 40])

In [ ]:
arr2[:4:3]

array([10, 40])

In [ ]:
arr2[::4]

array([10, 50])

In [ ]:
arr2[::]

array([10, 20, 30, 40, 50])

In [ ]:
for i in arr2:
  print(i)

10
20
30
40
50
