In [4]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [5]:
arr1

['pune', 'mumbai', 'surat', 'kolkata', 'bihar', 'jaipur', 'chennai']

In [6]:
print(arr1)

['pune', 'mumbai', 'surat', 'kolkata', 'bihar', 'jaipur', 'chennai']


In [7]:
type(arr1)

list

In [8]:
arr1[0]

'pune'

In [9]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [10]:
arr2

array([10, 20, 30, 40, 50])

In [11]:
print(arr2)

[10 20 30 40 50]


In [12]:
type(arr2)

numpy.ndarray

In [13]:
print(arr2)

[10 20 30 40 50]


In [14]:
arr2

array([10, 20, 30, 40, 50])

In [15]:
arr3 = numpy.array((100,200,300,400,500))

In [16]:
type(arr3)

numpy.ndarray

In [17]:
import numpy as np
a0 = np.array(10)

In [18]:
print(a0)

10


In [19]:
a0.ndim

0

In [20]:
a0

array(10)

In [21]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [22]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
a1.ndim
# # a1.ndim gives number of dimensions of the NumPy array


1

In [24]:
a1.shape 
a1.size
a1.dtype
a1.itemsize
a1.nbytes
a1.dtype.name
a1.astype('float64')
a1
a1.astype('int32')
a1.astype('int16')
a1.astype('int8')
a1.astype('uint8')
a1.astype('bool')
a1.astype('complex64')
a1.astype('complex128')
a1.astype('S4')
a1.astype('U4')
a1.astype('object')
a1.astype('float32')
a1.astype('float16')
a1.astype('float64')
a1.astype('int64')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [25]:
import numpy as np

a1 = np.array([1, 2, 3])

# a1.ndim → tells the number of dimensions (axes) of the array.
# For example: 
# 1D array → ndim = 1  (like [1,2,3])
# 2D array → ndim = 2  (like [[1,2,3],[4,5,6]])
# 3D array → ndim = 3  (like [[[1,2],[3,4]]])
print(a1.ndim)

1


In [26]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [27]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [28]:
a2 = np.array([
    [1, 2, 3],
    [10, 20, 30],
    [100, 200, 300],
    [1000, 2000, 3000]
])

# This creates a 2D NumPy array (matrix) with 4 rows and 3 columns:
# [
#   [1,     2,     3    ],
#   [10,    20,    30   ],
#   [100,   200,   300  ],
#   [1000,  2000,  3000 ]
# ]
# → Shape = (4, 3)
# → ndim = 2 (because it is a 2D array)
# → Each inner list represents one row


In [29]:
a2.ndim

2

In [30]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [31]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [32]:
a3.ndim

3

In [33]:
print("No. of dimensions:", a3.ndim)

No. of dimensions: 3


In [34]:
print("\033[91mNo. of dimensions:", a3.ndim, "\033[0m")
# --- IGNORE ---

No. of dimensions: 3 


In [35]:
print("\033[91mNo. of dimensions:", a3.ndim, "\033[0m")


No. of dimensions: 3 


In [36]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [37]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [38]:
a4.ndim

4

In [39]:
arr2 = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500]
])

print(arr2[0])     # → [10 20 30 40 50]
print(arr2[0][2])  # → 30


[10 20 30 40 50]
30


In [40]:
arr2[1],  [10,20,30,40,50]

(array([100, 200, 300, 400, 500]), [10, 20, 30, 40, 50])

In [41]:
a2[1,2], [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

(30, [[1, 2, 3], [10, 20, 30], [100, 200, 300], [1000, 2000, 3000]])

In [42]:
a2[2,2]

300

In [43]:
a3[0,0,0], [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

(1, [[[1, 2, 3], [10, 20, 30]], [[100, 200, 300], [1000, 2000, 3000]]])

In [44]:
a4[0,0,0,3]

4444

In [ ]:
a4[0,0,1,0]

IndexError: index 9 is out of bounds for axis 1 with size 1

You're getting this error because you're trying to access an index that does not exist in the 3rd axis (axis=2) of your NumPy array.

❗ Error meaning
IndexError: index 1 is out of bounds for axis 2 with size 1


This means:

Axis 2 (the third dimension) has size 1

You are trying to access index 1

Valid index is only 0

So a4[0,0,1,1] is invalid because the 3rd dimension index = 1 is out of range.

✅ How to fix it?

You must check the shape of your array a4 first:

print(a4.shape)


Suppose you get something like:

(2, 2, 1, 2)


This means:

axis 0 → size 2

axis 1 → size 2

axis 2 → size 1 ← ❗ problem

axis 3 → size 2

So valid indices:

Axis	Size	Valid indices
0	2	0–1
1	2	0–1
2	1	0 only
3	2	0–1
✔ Correct valid indexing example
a4[0, 0, 0, 1]   # axis 2 index must be 0

🎯 If you want axis 2 to have size > 1

Your array must contain more elements, for example:

a4 = np.random.randint(10, size=(2,2,2,2))
print(a4.shape)
# (2, 2, 2, 2)


Now this will work:

a4[0,0,1,1]

📌 Summary

You are accessing index 1 on axis 2 but that axis has size 1, so index 1 does not exist.
Only index 0 is allowed for that axis.

In [ ]:
print(a4.shape)

(1, 1, 1, 4)


In [47]:
a4.shape

(1, 1, 1, 4)

In [52]:
a12 = np.array([1,2,3])

In [55]:
a12[3] # IndexError: index 3 is out of bounds for axis 0 with size 3

IndexError: index 3 is out of bounds for axis 0 with size 3

In [56]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [57]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [58]:
arr2

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [59]:
arr2[-1]

array([100, 200, 300, 400, 500])

In [60]:
arr2[-2]

array([10, 20, 30, 40, 50])

In [61]:
arr2[1:]

array([[100, 200, 300, 400, 500]])

In [62]:
arr2[:3]

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [63]:
arr2[:]

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [64]:
arr2[1:4:1]

array([[100, 200, 300, 400, 500]])

In [ ]:
arr2[1:4:2] # means every 2nd element from index 1 to index 4 (excluding 4) will be printed out as a 1D array and not a 2D array of 1D arrays

array([[100, 200, 300, 400, 500]])

In [ ]:
arr2[:4:3] # means every 3rd element from the start to end of the array will be printed out as a 1D array and not a 2D array of 1D arrays

array([[10, 20, 30, 40, 50]])

In [ ]:
arr2[::4] # means every 4th element from the start to end of the array will be printed out as a 1D array and not a 2D array of 1D arrays

array([[10, 20, 30, 40, 50]])

In [68]:
arr2[::]

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [69]:
for i in arr2:
  print(i)

[10 20 30 40 50]
[100 200 300 400 500]
